spring.application.name=auth-service

server.port=4008

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

auth.jwt.issuer=ecommerce-auth
auth.jwt.audience=ecommerce-api
auth.jwt.access-token-ttl=15m
auth.jwt.key-id=ecommerce-auth-key-1

auth.jwt.public-key=file:${JWT_PUBLIC_KEY_PATH}
auth.jwt.private-key=file:${JWT_PRIVATE_KEY_PATH}
