spring.application.name=customer-service

server.port=4001

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:dev/db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never