spring.application.name=payment-service

server.port = 4007

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

spring.jpa.properties.hibernate.type.json_format_mapper=jackson3

# stripe
payment.stripe.secret-key=${STRIPE_SECRET_KEY}
payment.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
payment.stripe.success-url=http://localhost:4002/payments/success
payment.stripe.cancel-url=http://localhost:4002/payments/cancel

# kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# outbox relay
outbox.relay.enabled=true
outbox.relay.fixed-delay-ms=2000

kafka.topic.payment-commands=payment.commands
kafka.topic.payment-commands-dlt=payment.commands.DLT
kafka.topic.payment-events=payment.events

#consumer
spring.kafka.consumer.group-id=payment-service

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=dev.erkut.paymentservice.message.MessageEnvelope

# producer
spring.kafka.producer.client-id=payment-service-producer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
