### Add address
POST {{customerBaseUrl}}/customers/{{customerId}}/addresses
Content-Type: application/json

{
  "fullAddress": "Bagdat Caddesi No 100 Kadikoy",
  "city": "Istanbul",
  "country": "Turkey"
}


### Add address to inactive customer - expect 409
POST {{customerBaseUrl}}/customers/{{inactiveCustomerId}}/addresses
Content-Type: application/json

{
  "fullAddress": "Test Address No 10",
  "city": "Istanbul",
  "country": "Turkey"
}


### Remove address
DELETE {{customerBaseUrl}}/customers/{{customerId}}/addresses/a0000000-0000-0000-0000-000000000001