### Get customer by id
GET {{customerBaseUrl}}/customers/{{customerId}}


### Get inactive customer
GET {{customerBaseUrl}}/customers/{{inactiveCustomerId}}


### Get customers - first page
GET {{customerBaseUrl}}/customers?page=0&size=10


### Get customers - second page
GET {{customerBaseUrl}}/customers?page=1&size=10


### Invalid page - expect 400
GET {{customerBaseUrl}}/customers?page=-1&size=10


### Customer not found - expect 404
GET {{customerBaseUrl}}/customers/99999999-9999-9999-9999-999999999999