package dev.erkut.orderworkflowservice.saga.domain;

public enum OrderSagaState {
    STOCK_RESERVATION_PENDING,
    PAYMENT_PENDING,
    PAYMENT_UNKNOWN,
    STOCK_CONFIRMATION_PENDING,
    ORDER_CONFIRMATION_PENDING,
    STOCK_RELEASE_PENDING,
    COMPLETED,
    FAILED,
    ORDER_REJECTION_PENDING
}