### Deactivate product
POST {{productBaseUrl}}/products/{{productId}}/deactivate


### Deactivate already inactive product
POST {{productBaseUrl}}/products/{{inactiveProductId}}/deactivate


### Delete product
DELETE {{productBaseUrl}}/products/{{productId}}


### Delete missing product - expect 404
DELETE {{productBaseUrl}}/products/99999999-9999-9999-9999-999999999999