spring.application.name=order-service

server.port=4000

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:dev/db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

restclient.customer.url=${CUSTOMER_SERVICE_URL:http://localhost:4001/customers}

spring.http.clients.connect-timeout=2s
spring.http.clients.read-timeout=3s
