spring.application.name=order-service

server.port=4000

management.server.port=9090
management.endpoints.web.exposure.include=health,prometheus
management.endpoints.web.discovery.enabled=false
management.metrics.distribution.percentiles-histogram.http.server.requests=true

management.tracing.sampling.probability=1.0
management.opentelemetry.resource-attributes[service.name]=order-service
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://tempo:4318/v1/traces}
management.otlp.metrics.export.enabled=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:dev/db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

restclient.customer.base-url=${CUSTOMER_SERVICE_BASE_URL:http://localhost:4001}
restclient.product.url=${PRODUCT_SERVICE_URL:http://localhost:4003/products}

spring.http.clients.connect-timeout=2s
spring.http.clients.read-timeout=3s

# to be sure about json format mapper version
spring.jpa.properties.hibernate.type.json_format_mapper=jackson3

# outbox relay ms
outbox.relay.enabled=true
outbox.relay.fixed-delay-ms=2000

## kafka config
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# kafka consumer
spring.kafka.consumer.group-id=order-service
spring.kafka.listener.observation-enabled=true
spring.kafka.consumer.properties.allow.auto.create.topics=false

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=dev.erkut.orderservice.message.MessageEnvelope

# kafka producer
kafka.topic.order-events=order.events
kafka.topic.order-commands=order.commands
kafka.topic.order-commands-dlt=order.commands.DLT

spring.kafka.producer.client-id=order-service-producer
spring.kafka.template.observation-enabled=true

spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
##

## security
security.jwt.public-key= file:${JWT_PUBLIC_KEY_PATH}
security.jwt.issuer=ecommerce-auth
security.jwt.audience=ecommerce-api
