spring.application.name=product-service

server.port = 4003

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:dev/db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

spring.jpa.properties.hibernate.type.json_format_mapper=jackson3

# outbox
outbox.relay.enabled=true
outbox.relay.fixed-relay-ms=2000

# kafka
kafka.topic.product-events=product.events

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# producer
spring.kafka.producer.client-id=product-service
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false
