spring.application.name=product-service

server.port = 4003

management.server.port=9090
management.endpoints.web.exposure.include=health,prometheus
management.endpoints.web.discovery.enabled=false
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:0.1}
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://tempo:4318/v1/traces}
management.otlp.metrics.export.enabled=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:dev/db/migration

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=never

spring.jpa.properties.hibernate.type.json_format_mapper=jackson3

# security
security.jwt.public-key= file:${JWT_PUBLIC_KEY_PATH}
security.jwt.issuer=ecommerce-auth
security.jwt.audience=ecommerce-api

# outbox
outbox.relay.enabled=true
outbox.relay.fixed-relay-ms=2000

# kafka
kafka.topic.product-events=product.events

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# producer
spring.kafka.producer.client-id=product-service
spring.kafka.template.observation-enabled=true
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false
