### Create order
POST {{orderBaseUrl}}/orders
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "currency": "TRY",
  "items": [
    {
      "itemId": "d0000000-0000-0000-0000-000000000001",
      "quantity": 1
    },
    {
      "itemId": "d0000000-0000-0000-0000-000000000002",
      "quantity": 2
    },
    {
      "itemId": "d0000000-0000-0000-0000-000000000002",
      "quantity": 2
    }
  ]
}


### Create order for inactive customer - expect 409
POST {{orderBaseUrl}}/orders
Content-Type: application/json

{
  "customerId": "{{inactiveCustomerId}}",
  "currency": "TRY",
  "items": [
    {
      "itemId": "{{productId}}",
      "quantity": 1
    }
  ]
}


### Create order with invalid customer - expect 404
POST {{orderBaseUrl}}/orders
Content-Type: application/json

{
  "customerId": "99999999-9999-9999-9999-999999999999",
  "currency": "TRY",
  "items": [
    {
      "itemId": "{{productId}}",
      "quantity": 1
    }
  ]
}