### Add item
POST {{orderBaseUrl}}/orders/{{orderId}}/items
Content-Type: application/json

{
  "itemId": "d0000000-0000-0000-0000-000000000004",
  "quantity": 2
}


### Change item quantity
PATCH {{orderBaseUrl}}/orders/{{orderId}}/items/d0000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "quantity": 3
}


### Remove item
DELETE {{orderBaseUrl}}/orders/{{orderId}}/items/d0000000-0000-0000-0000-000000000002


### Invalid quantity - expect 400
PATCH {{orderBaseUrl}}/orders/{{orderId}}/items/d0000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "quantity": 0
}