package dev.erkut.orderworkflowservice.outbox.domain;

public enum OutboxMessageType {
    RESERVE_STOCK_COMMAND,
    REJECT_ORDER_COMMAND,
    INITIATE_PAYMENT_COMMAND,
    CONFIRM_STOCK_RESERVATION_COMMAND,
    MARK_ORDER_STOCK_RESERVED_COMMAND,
    MARK_ORDER_PAYMENT_COMPLETED_COMMAND,
    CONFIRM_ORDER_COMMAND
}
